client/src/components/AreaFilter.js, client/src/components/Layout.js, client/src/components/MessageModal.js, client/src/pages/MyPage.js, client/src/pages/NoticeCreate.js, client/src/pages/NoticeDetail.js, client/src/pages/NoticeList.js, client/src/pages/ProgCreate.js, client/src/pages/ProgUpdate.js
레이아웃 완성해서 PR합니다.
page 만드실때 Layout.js 임포트 하시고 진행하시면 됩니다.
제가 목업 맡은 page는 파일만 만들어두었습니다.
=> [FE] feat: Layout.js & page file

client/src/components/AreaFilter.tsx
지역 필터 드롭다운 완성해서 PR합니다.
사용은 일반 컴포넌트 사용과 동일합니다.
추가로 드롭다운 컨테이너와 드롭다운 리스트의 레이아웃도 AreaFilter.js에서 export 해놨습니다.
파일 보시고 참고해주시면 될 것 같습니다.
=> [FE] feat: AreaFilter

client/src/App.tsx, client/src/components/Header.tsx, client/src/pages/NoticeDetail.tsx, client/src/pages/NoticeList.tsx, client/src/pages/ProgCreate.tsx
작업 내용
1. 공지사항 리스트 조회 페이지 목업
2. 페이지 URL 수정
=> [FE] feat: Notice List Page & fix: Page URL

server/src/main/java/com/codestates/team5/dailyclub/config/WebConfig.java
change cors origin port 3030 to 3000
=> [BE] fix: fix cors origin port

server/build.gradle, server/src/main/java/com/codestates/team5/dailyclub/common/mapper/CommonMapper.java, server/src/main/java/com/codestates/team5/dailyclub/config/QuerydslConfig.java, server/src/main/java/com/codestates/team5/dailyclub/image/util/ImageUtils.java, server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java, server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java, server/src/main/java/com/codestates/team5/dailyclub/program/dto/SearchFilterDto.java, server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepository.java, server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepositoryCustom.java, server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepositoryImpl.java, server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java, server/src/main/java/com/codestates/team5/dailyclub/user/mapper/UserMapper.java, server/src/main/resources/application.yml
Querydsl로 동적 쿼리를 생성해 프로그램 검색/필터링 기능 구현한 코드입니다.
* UserMapper 오타 부분 수정하고, User -> UserResponseDto 메소드 CommonMapper로 이동했습니다. 
그리고 @Mapper에서 Bean으로 등록하는 코드 바뀌어서 수정했습니다.
=> [BE] feat: search programs by Querydsl

server/src/main/java/com/codestates/team5/dailyclub/config/SecurityConfig.java, server/src/main/java/com/codestates/team5/dailyclub/jwt/filter/JwtAuthenticationFilter.java
[BE] fix: addExposeHeader "Refresh"
=> [BE] fix: addExposeHeader "Refresh"

server/src/main/java/com/codestates/team5/dailyclub/config/SecurityConfig.java
Security ignoring에 "/api/docs" 추가했습니다.
=> [BE] fix: Security ignoring

client/src/pages/MyPage.tsx, client/src/types/user.tsx
- 마이페이지에서 get 요청으로 회원 정보를 조회할 수 있도록 코드 작성
- types 디렉토리의 user.tsx 파일 수정
- 규칙(interface) 추가(?)
=> [FE]feat: User-info-lookup

client/src/pages/MyPage.tsx, client/src/types/user.tsx
- 마이페이지에서 '회원탈퇴' 버튼 클릭시 '확인을 누르면 회원 정보가 삭제됩니다.' 라는 팝업 메시지가 표시됨.
- 확인 버튼을 클릭하면 '그동안 이용해주셔서 감사합니다.' 라는 팝업 메시지와 함께 회원 정보가 삭제되고, 메인 페이지로 이동함.
- 콘솔까지 확인한 결과, 에러없이 작동했습니다.
=> [FE]feat: User-info-delete

client/src/App.tsx, client/src/components/ApplyModal.tsx, client/src/components/CancelModal.tsx, client/src/components/DeleteModal.tsx, client/src/components/MessageModal.tsx, client/src/pages/ProgDetail.tsx
작업내용
1. 프로그램 신청, 삭제, 신청취소에 대한 유저행동을 다시 한번 확인시켜주는 모달 목업과 API 구현
2. 메시지 보내기 모달 목업 구현
=> FE] feat: Modal Api

server/src/main/java/com/codestates/team5/dailyclub/common/util/EnumValueConvertUtils.java, server/src/main/java/com/codestates/team5/dailyclub/image/entity/ProgramImage.java, server/src/main/java/com/codestates/team5/dailyclub/image/util/ImageUtils.java, server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java, server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java, server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/advice/GlobalExceptionAdvice.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/dto/ErrorResponseDto.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/BusinessLogicException.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/ExceptionCode.java, server/src/main/java/com/codestates/team5/dailyclub/validator/annotation/Image.java, server/src/main/java/com/codestates/team5/dailyclub/validator/annotation/Location.java, server/src/main/java/com/codestates/team5/dailyclub/validator/annotation/TodayOrAfter.java, server/src/main/java/com/codestates/team5/dailyclub/validator/validator/ImageValidator.java, server/src/main/java/com/codestates/team5/dailyclub/validator/validator/LocationValidator.java, server/src/main/java/com/codestates/team5/dailyclub/validator/validator/TodayOrAfterValidator.java, server/src/main/resources/application.yml, server/src/main/resources/errors.properties
@ControllerAdvice 로 예외 공통 처리를 진행했고,
fieldError 메시지 처리를 error 메시지 파일(errors.properties)을 만들어서 한 번에 관리하도록 했습니다.
특히, 기본으로 주어지는 annotation validator 뿐만 아니라 @Image, @TodayOrAfter와 같이 필요한 annotation validator를 custom으로 만들었습니다.
BusinessLogicException이라고 Custom Exception을 만들어 각 상황에 맞는 Exception Code를 추가해 적절하게 사용할 수 있도록 했습니다.
=> [BE] feat: handle global error

server/src/main/java/com/codestates/team5/dailyclub/apply/controller/ApplyController.java, server/src/main/java/com/codestates/team5/dailyclub/apply/dto/ApplyDto.java, server/src/main/java/com/codestates/team5/dailyclub/apply/repository/ApplyRepository.java, server/src/main/java/com/codestates/team5/dailyclub/apply/service/ApplyService.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/ExceptionCode.java, server/src/main/resources/errors.properties
1. 기본적인 CRUD 기능입니다. (+로그인 유저)
2. 요구사항에 정의 되어있는 유효성 검사 + 비즈니스 로직은 ApplyService에 있습니다. (알림 부분 제외)
-> 유효성 검사 때문에 Query가 더 많이 나가게 되는데 나중에 리팩토링할 예정입니다.
3. 신청 등록/삭제 후 프로그램 인원 상태 업데이트 하는 로직이 ProgramService에 있어서 ApplyService가 PrgramService를 현재 의존하고 있습니다. 추후 문제가 있을 시 수정 가능합니다.
=> [BE] feat: Apply CRUD + validation

server/src/main/java/com/codestates/team5/dailyclub/common/mapper/CommonMapper.java, server/src/main/java/com/codestates/team5/dailyclub/image/dto/UserImageDto.java, server/src/main/java/com/codestates/team5/dailyclub/image/entity/UserImage.java, server/src/main/java/com/codestates/team5/dailyclub/image/mapper/UserImageMapper.java, server/src/main/java/com/codestates/team5/dailyclub/image/repository/UserImageRepository.java, server/src/main/java/com/codestates/team5/dailyclub/image/util/ImageUtils.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/ExceptionCode.java, server/src/main/java/com/codestates/team5/dailyclub/user/controller/UserController.java, server/src/main/java/com/codestates/team5/dailyclub/user/dto/UserDto.java, server/src/main/java/com/codestates/team5/dailyclub/user/entity/User.java, server/src/main/java/com/codestates/team5/dailyclub/user/service/UserService.java
유저 이미지(프로필 사진) 등록 부분을 임시로 String으로 진행했는데 실제 기능이 가능하도록 구현하였습니다.
ExcepctionCode에 유저 이미지 관련 부분을 추가하였습니다.
rebase를 진행하는 과정에서 commitmessage가 바뀌었습니다. 
[BE] rebase -> [BE] fix: User Image and Exception
=> [BE] fix : Add user image registration

server/src/main/java/com/codestates/team5/dailyclub/bookmark/controller/BookmarkController.java, server/src/main/java/com/codestates/team5/dailyclub/bookmark/dto/BookmarkDto.java, server/src/main/java/com/codestates/team5/dailyclub/bookmark/entity/Bookmark.java, server/src/main/java/com/codestates/team5/dailyclub/bookmark/mapper/BookmarkMapper.java, server/src/main/java/com/codestates/team5/dailyclub/bookmark/repository/BookmarkRepository.java, server/src/main/java/com/codestates/team5/dailyclub/bookmark/service/BookmarkService.java
1. 기본 Bookmark CRUD (+로그인 유저)
2. Apply와 마찬가지로 유효성 검증 + 비즈니스 로직에 의한 Query가 나가서 줄이는 방안으로 리팩토링할 예정입니다.
3. Foreign Key로 검색할 때 Entity로 가능
-> BookmarkRepository.java에서 보면 foreign key를 wherer절에서 사용할 때 id를 parameter로 직접 주지 않고 엔티티로 parameter를 설정해도 동작합니다.
```java
public interface BookmarkRepository extends JpaRepository <Bookmark, Long> {
boolean existsByUserAndProgram(User userById, Program programById);
//생략
Bookmark findFirstByUserAndProgram(User userById, Program programById);
}
```
=> [BE] feat: Bookmark CRUD + validation

server/src/main/java/com/codestates/team5/dailyclub/jwt/AuthDetails.java, server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java, server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java, server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepository.java, server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
* 요구사항 정의서에 적혀있는 validation은 알림 제외하고는 추가했습니다.
* 프로그램 1개나 리스트 조회 시 로그인한 유저가 북마크 했는지 추가하는 로직은 전에 Pre 때처럼 responseDto 다 만들고서 그 뒤에 따로 진행했습니다. (in Controller)
```java
//로그인 유저가 해당 프로그램 북마크 했는지 체크하고, bookmarkId setting하는 메소드
private void checkBookmark(Long loginUserId, Long programId, ProgramDto.Response response) {
Long bookmarkId = bookmarkService.findBookmark(loginUserId, programId);
response.setBookmarkId(bookmarkId);
}
```
=> [BE] feat: program validation

client/src/App.tsx, client/src/components/ApplyModal.tsx, client/src/components/CancelModal.tsx, client/src/components/DeleteModal.tsx, client/src/pages/ProgDetail.tsx
작업내용 
1. 신청 요청 보낸후 신청자 리스트 리로드
2. 로그인 유저id 고정 수정
=> [FE] fix: reload Apply List

client/src/App.tsx, client/src/components/CancelModal.tsx, client/src/components/Header.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgCreate.tsx, client/src/pages/ProgDetail.tsx, client/src/pages/ProgUpdate.tsx, client/src/types/user.tsx
작업내용
1. 이미지, 닉네임, 자기소개 수정기능 성공
2. 프로그램 신청 취소 테스트 성공
=> [Fe] feat update user

client/src/pages/MyPage.tsx
- ### 프로그램 리스트 조회 완료
- 참여 중인 모임(제목, 설명, 날짜, 상태)
- 개설한 모임(제목, 설명, 날짜, 상태)
완료된 부분까지 PR합니다.
조회된 리스트를 클릭하면 해당 프로그램의 상세 페이지로 이동합니다.
프로그램 이미지 조회는 구현하지 못했습니다.
프로그램이 종료되었거나, 현재 날짜보다 이전일 때 이미지가 변경되어야 하는 작업은 아직 진행 중입니다.
~_API 작업 중에 API 문서를 잘 못 이해해서 장시간 삽질을 해버림.. 삽질했다는 것을 깨닫고 코드 작성한 순간에 분노를 느낌._~
=> [FE] feat: mypage program list 조회

server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java, server/src/main/java/com/codestates/team5/dailyclub/program/dto/SearchFilterDto.java, server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepositoryImpl.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/advice/GlobalExceptionAdvice.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/dto/ErrorResponseDto.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/ExceptionCode.java, server/src/main/java/com/codestates/team5/dailyclub/validator/annotation/ProgramStatus.java, server/src/main/java/com/codestates/team5/dailyclub/validator/validator/ProgramStatusValidator.java, server/src/main/java/com/codestates/team5/dailyclub/validator/validator/TodayOrAfterValidator.java, server/src/main/resources/errors.properties
1. 등록/수정할 때랑 검색할 때랑 조건이 달라져서 추가했습니다.
-> 등록/수정할 때에는 programDate 필드가 필수이지만 검색일 때는 null을 허용하면서, 값이 있을 때만 형태를 맞춰야 해서, Custom annotation 부분에서 기본적으로 null을 허용하는 것으로 바꾸고, 등록/수정일 때에 @NotNull validation을 추가했습니다.
2. 검색 조건에 프로그램 시작 날짜가 없을 경우에는 오늘 날짜 포함 그 이후에 시작하는 프로그램만 나오게 querydsl 조건문을 바꿨습니다.
3. 원래는 업로드 하려는 이미지 사이즈가 10MB 이상일 때, 요청이 Controller에 도달하기 전에 Spring이 먼저 Exception을 발생하기 때문에 @ControllerAdvice에서 해당 Exception을 처리하지 못하는데 application.yml에 추가한 
```
spring:
servlet:
multipart:
max-file-size: 10MB
max-request-size: 10MB
```
이 설정때문에 @ControllerAdvice에서 해당 exception을 처리할 수 있어서 MaxUploadSizeExceededException 핸들러 메서드를 추가했습니다.
4. @ProgramStatus annotation을 만들었습니다. "모집중", "마감임박", "마감" 이 세 가지 문자열이 아닐 경우 validation에 걸리게끔 하는 annotation입니다. SearchFilterDto에서 사용합니다.
5. errors.properties에 error message를 추가했습니다.
=> [BE] feat: add more validation for program CRUD & search

client/src/components/Header.tsx, client/src/components/Tab/BookMarkTab.tsx, client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgCreate.tsx, client/src/pages/ProgDetail.tsx, client/src/types/user.tsx, client/src/utils/byteToBase64.ts, client/src/utils/compareWithToday.ts, client/src/utils/getToday.ts
1. bookmark
- 메인 - 북마크 등록/삭제
- 글 상세 - 북마크 등록/삭제 (본인 글에서도 북마크 버튼 활성화)
- 마이페이지 북마크 탭 - 북마크 삭제
2. Header Link 추가
- 홈, 모임목록
3. 프로필수정시 회원조회로 전역상태 갱신 => Header Img에 반영하기
4. Header 프로필 - 색상 주황색으로 수정
5. 마이페이지 종료
- compareWithToday.ts - 오늘날짜랑 프로그램날짜 비교해서 모임종료, 오늘마감, 모임예정 문자열 출력
- 사용예시 - components/Tab/BookMarkTab에서 사용함
1. 마이페이지 프로그램에서 모임종료 메시지 출력하기
`{compareWithToday(el?.program?.programDate)}` :  인자로 programDate를 넘겨야 합니다
2.  마이페이지 프로그램에서 모임종료면 사진에 겹쳐서 종료 메시지 띄우기 예시
```
{compareWithToday(el?.program?.programDate) === '모임종료'
? '종료'
: null}
```
- 분리 이유 - 달력 Input에서 이전날짜 비활성화하는게 중복 사용되므로 파일로 분리함
- 사용처 - 모임목록 날짜, 글 등록 날짜
- 사용예시 ` min={getToday()}`
- 분리 이유 - 이미지있을 때 bytes를 base64로 변환하여 img src에 넣는게 중복되므로 파일로 분리함
인자 2개 전달하기
- 첫번째: contentType 전달
- 두번째: bytes 전달
- 예시 (Header 275줄)
```
<img
src={ …
```
=> [FE] feat: 

client/src/components/ApplyModal.tsx, client/src/components/CancelModal.tsx, client/src/components/DeleteModal.tsx, client/src/pages/Login.tsx, client/src/pages/ProgCreate.tsx, client/src/pages/ProgDetail.tsx, client/src/pages/ProgUpdate.tsx
작업내용
1. 프로그램 작성, 수정, 신청, 신청취소, 삭제, 로그인에 대한 유효성 체크하기
alert 팝업으로 사용자에게 정보 전달
특이사항
진행날짜가 지난 프로그램도 신청이 된다, 신청 취소도 물론 된다
페이지 렌더링 속도 때문에 유효성체크에 어려움이 있음
모집이 완료된 프로그램은 아직 메인에 보여지지 않아서 테스트 불가
=> [FE] feat: validation check

server/src/main/java/com/codestates/team5/dailyclub/apply/controller/ApplyController.java, server/src/main/java/com/codestates/team5/dailyclub/apply/entity/Apply.java, server/src/main/java/com/codestates/team5/dailyclub/apply/service/ApplyService.java, server/src/main/java/com/codestates/team5/dailyclub/review/controller/ReviewController.java, server/src/main/java/com/codestates/team5/dailyclub/review/dto/ReviewDto.java, server/src/main/java/com/codestates/team5/dailyclub/review/service/ReviewService.java, server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/ExceptionCode.java, server/src/main/java/com/codestates/team5/dailyclub/user/entity/User.java
```json
{
"applyId" : 1,
"likes" : [
1, 9, 10
],
"hate" : 3,
"score" : -2
}
```
→ 201 [CREATED], “success” 로 응답
→ `/api/reviews`
→ 유효성 검사 (유저 존재, 신청 존재, 본인이 리뷰 남기는지, 이미 리뷰 남겼는지 확인)
→ 각 문항에 맞는 유저 친절 % 업데이트
→ Apply의 review status를 `UNREVIEWED`에서 `REVIEWED` 로 업데이트
* like : +1
* hate : -1
* score(writer) : -2, -1, 0, 1, 2
=> [BE] feat: create review + update Apply review status

client/src/pages/MyPage.tsx, client/src/pages/ProgDetail.tsx, client/src/types/programs.tsx
작업 내용
1. 신청자 리스트 이미지 처리, 작성자 이미지 처리
2. 신청자, 작성자 프로필 클릭 시 유저페이지로 이동
=> [Fe] fix: programdetail page apply user img & user link 

client/src/pages/MyPage.tsx
- ## 마이페이지 분기 구현
- ### 유저 2가 유저 1의 마이페이지로 이동했을 때
- 모임 탭의 이름이 유저 1의 모임으로 보이도록 수정했습니다.
- ### 유저 2가 자신(유저 2)의 마이페이지로 이동했을 때
- 코드를 보시면 확인할 수 있듯이 코드가 매우 지저분하게 작성되었습니다..
- 이번에도 삽질을 오래 했지만, 리스트 조회에 비해서는 많은 것을 배움.
=> [FE] feat: Mypage Branch

client/src/components/CancelModal.tsx, client/src/pages/Login.tsx, client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgCreate.tsx, client/src/pages/ProgDetail.tsx, client/src/pages/ProgUpdate.tsx, client/src/pages/SignUp.tsx
작업내용
1. 로그인, 회원가입, 이미지용량, 최소 친절 신청을 제외한 프론트엔드 1차 유효성검사 구현완료
2. 마이페이지 useEffect 중복 제거
특이사항
로그인(서버 에러에서 발생시 아이디 비밀번호 틀림 팝업),  회원가입(아직 프론트단에서 고유 아이디, 이메일, 닉네임 판별 불가), 
이미지용량(따로 제한할 수 있는 방법이 없음), 최소 친절 신청(전역 상태 유저정보에 친절도 필요)
=> [Fe] feat: validation check in client  

server/src/main/java/com/codestates/team5/dailyclub/apply/service/ApplyService.java, server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
메인 페이지에서 필요한 신청 인원 작업입니다.
검색 조회 Controller 메소드에서 responseDto에 numOfApplicatnts 세팅하는 로직 추가했습니다.
applyService에 각 programId로 리스트 조회 후 사이즈를 리턴하는 메소드를 선언했습니다.
=> [BE] feat: add numOfApplicants field to ProgramResponseDto for Main Page

server/src/main/java/com/codestates/team5/dailyclub/apply/controller/ApplyController.java, server/src/main/java/com/codestates/team5/dailyclub/bookmark/controller/BookmarkController.java, server/src/main/java/com/codestates/team5/dailyclub/review/controller/ReviewController.java
각종 엔티티 삭제 요청 시 응답 값이 없었는데 String으로 메시지를 추가했습니다.
=> [BE] chore: add String message to DELETE response body

server/src/main/java/com/codestates/team5/dailyclub/apply/dto/ApplyDto.java, server/src/main/java/com/codestates/team5/dailyclub/apply/mapper/ApplyMapper.java
Review 작성 여부 Column 값 ResponseDto에 추가한 작업입니다.
mapper에서 mapping 해주는 작업도 추가했습니다.
=> [BE] chore: add responseStatus field to ApplyResponseDto

client/src/App.tsx, client/src/components/CheckBox.tsx, client/src/components/Header.tsx, client/src/components/Tab/BookMarkTab.tsx, client/src/pages/Login.tsx, client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgCreate.tsx, client/src/pages/ProgUpdate.tsx, client/src/pages/ReviewCreate.tsx, client/src/styles.tsx
- 문제 - input에 all:unset 때문에 input type='checkbox'가 안보임
- 전역 input style에서 all:unset 삭제하고 나서 모양 이상해진 input 각각에 all:unset 추가
- 링크 `/programs/:programId/reviews/:applyId` - 멤버조회시 programId가 필요해서 다시 추가함
- 함께 하고 싶은 멤버 - 중복선택
- 나머지 항목 - 1개만 선택
- Login 후 이전 페이지로 이동시키기
- MyPage, BookmarkTab css 수정함
- 마이페이지 분기 추가 - 회원탈퇴,로그아웃,리뷰버튼은 남이 보는 페이지에서 안보이게 하기
=> [FE] feat: Review api, css 수정

server/src/main/java/com/codestates/team5/dailyclub/config/SecurityConfig.java, server/src/main/java/com/codestates/team5/dailyclub/jwt/filter/JwtAuthenticationFilter.java, server/src/main/java/com/codestates/team5/dailyclub/user/controller/UserController.java, server/src/main/java/com/codestates/team5/dailyclub/user/service/UserService.java
로그인 성공과 실패시 응답 메세지를 작성하였고 로그아웃 컨트롤러를 구현해서 refreshToken을 삭제하였습니다.
=> [BE] fix: login success and fail message and add logout

client/src/components/CheckBox.tsx, client/src/components/Header.tsx, client/src/components/Tab/BookMarkTab.tsx, client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgDetail.tsx
- 프로그램 전체 최신순으로 뜨게 만들기
- 홈 눌렀을 때 히어로페이지 말고 프로그램으로 가도록 하기
- 신청된 것만 북마크가 되고 마이페이지도 그것만 보여지는 것 수정 - 신청안한것도 북마크 가능하게 수정
- 프로그램 종료시 글자 왼쪽으로 치우쳐져 있는 것 - 글자크기 및 css 수정
- 프로그램 목록, 마이페이지(내모임,북마트 탭) - 제목/내용 길어지는 것만 ... 추가
=> [FE] chore: 글자길어지면 ...추가, Header 링크, Bookmark

client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgDetail.tsx, client/src/pagination/Pagination.tsx
전달사항
- 페이지 네이션 사용하실 때 useEffect() 의존성 배열에 Page 넣어주셔야 사용 가능 합니다
=> [Fe] 프로그램 수정 및 삭제 유효성 검사 수정 과 페이징 처리 수정

client/src/components/Header.tsx, client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgDetail.tsx
- 마이페이지 리뷰작성하면 리뷰완료+회색으로 버튼 모양 바꾸기
- 로그인 안하고 
- 상세페이지 - 신청하기, 북마크, 메시지보내기 클릭 시 Login 페이지로 이동
- 메인 - 북마크 클릭 시 Login 페이지로 이동
- Header 마이페이지, 프로필 이미지 클릭 시 프로필 박스 닫기
- Header  프로필 박스에 친절도 추가
- 메인 카드 맨 오른쪽 여백 없애기
> 주말에 한거랑 오전에 수정한 거 PR합니다
=> [FE] chore: 리뷰완료버튼 / 로그인 안하고 북마크,신청,메시지보내기 클릭시 로그인페이지로 이동 / 헤더 프로필박스 / 메인 카드

client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgCreate.tsx, client/src/pages/ProgUpdate.tsx
작업내용
1. 메인, 글 작성 및 수정 페이지 Input 요소 UI/UX 수정 (커서, 날짜 년도 4자리만 입력 등)
2. 프로필이미지 수정 작업 완료
=> [FE] fix: user profile update & input css

client/src/components/AreaFilter.tsx, client/src/components/KindGuide.tsx, client/src/pages/Login.tsx, client/src/pages/Main.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgDetail.tsx, client/src/stores/filterSlice.ts, client/src/stores/store.ts
- 모집상태 하이라이트
- 친절도 호버시 설명박스 - KindGuide
- 메인-친절도필터 / 상세-모임장,신청인원 / 마이페이지-프로필 에 추가함
- 필터에서 지역(전체),날짜(삭제),친절도(초기화) -  초기화 버튼
- 필터 전역상태 저장은 했는데
- 메인에서 useEffect에서 params 갱신함수에 넣어줬는데 안들어감..
- 날짜에서 삭제버튼 누르면 전역상태에서도 삭제되어야 하는데, input date에 삭제버튼에 어떻게 접근해야 하는지 찾아봐야함
=> [FE] 모집상태하이라이트, 필터조건 각각 초기화버튼, 친절도 설명박스

client/package-lock.json, client/package.json, client/src/components/MessageModal.tsx, client/src/pages/MyPage.tsx, client/src/pages/ProgDetail.tsx
작업내용
메시지 모달 변경 (마이페이지, 상세페이지)
특이사항
메시지 함은 변경하려면 목업 자체를 변경해야해서 따로 수정하지 않았습니다.
=> [FE] fix: message Modal

client/src/components/Header.tsx, client/src/utils/timeForToday.ts
작업내용
1. 신청완료 및 프로그램 업데이트에 대한 알림기능
특이사항
헤더 프로필 버튼을 눌러야 조회가 가능하다
=> [FE] feat: notification

client/src/components/ApplyModal.tsx, client/src/components/MessageModal.tsx, client/src/pages/Hero.tsx, client/src/pages/ProgCreate.tsx, client/src/pages/ProgDetail.tsx, client/src/pages/ProgUpdate.tsx
작업내용
1. 서비스 소개 페이지 반응형
2. 프로그램 상세 페이지 반응형
3. 프로그램 작성, 수정 페이지 반응형
특이사항
작성 및 수정 페이지 모바일로 인풋 잘 작동하는지 확인 필요
=> [FE] feat: responsive web Hero, Detail, Create, Update

client/src/pages/MyPage.tsx, client/src/pages/ProgDetail.tsx, client/src/pages/ReviewCreate.tsx
- 반응형 구현
- 마이페이지
- 리뷰 작성 페이지
- 데이터가 없을 때
- 신청한, 개설한 모임이 없을 때
- 신청자가 없을 때
마이페이지에서 종료된 모임의 이미지의 '종료' 텍스트가 깨져있음.
검색 결과가 없을 때 문구 띄우기 구현X
마이페이지 리스트들 더보기 대신 페이지네이션으로 구현함. ~~(어떻게 하징?)~~
=> [FE] feat: responsive mypage, reviewpage etc..
